version: "3"
networks:
  ztech:

services:
   nginx:
      image: nginx:stable-alpine
      container_name: ztech-nginx
      ports:
        - 8082:80
      volumes:
        - ./src:/var/www
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php
        - mysql
      networks:
        - ztech
   mysql:
      image: mysql:8.0
      container_name: ztech-mysql
      restart: unless-stopped
      tty: true
      ports:
        - 3309:3306
      environment:
        - MYSQL_DATABASE=${DB_DATABASE}
        - MYSQL_USER=${DB_USERNAME}
        - MYSQL_PASSWORD=${DB_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        - SERVICE_TAGS=dev
        - SERVICE_NAME=mysql
      networks:
        - ztech
   php: 
      build:
        context: .
        dockerfile: Dockerfile
      container_name: ztech-php
      volumes:
        - ./src:/var/www
      ports:
        - 9000:9000
      networks:
        - ztech

     