version: "3.8"
services:
  php:
    build:
      args:
        user: dotman
        uid: 1000
      context: .
      target: php
      dockerfile: Dockerfile
    container_name: techfair-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - techfair

  database:
    image: mysql:8.0
    container_name: techfair-db
    ports:
      - 3307:3306
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - techfair

  nginx:
    image: nginx:stable-alpine
    container_name: techfair-nginx
    restart: unless-stopped
    ports:
      - 8090:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/techfair.conf:/etc/nginx/conf.d/default.conf
    networks:
      - techfair
    depends_on:
      - php
      - database

volumes:
  db-data: ~

networks:
  techfair:
    driver: bridge