name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Directory Permissions
        run: chmod -R 775 storage/logs bootstrap/cache
      - name: Deploy to production
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |

            cd /var/www/html/projects/zenith-techfair

            git checkout -f

            git pull

            npm install

            npm run build

            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev -o

            php artisan key:generate

            php artisan migrate --force

            php artisan db:seed --force

            php artisan view:cache

            php artisan route:cache

            php artisan config:cache

            php artisan up

